name: Production

on:
  push:
    tags:
      - '*'

jobs:
  shared:
    uses: BlusparkTeam/github-workflows/.github/workflows/build-deploy-superset.yaml@main
    secrets: inherit
    with:
      environment: prod
